steps:
  # Pull previous image
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - 'docker pull gcr.io/$PROJECT_ID/$_IMAGE_NAME:latest || exit 0'
    entrypoint: bash

  # Build image
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - >
        docker build -t \

        gcr.io/$PROJECT_ID/$_IMAGE_NAME:${BRANCH_NAME}_${SHORT_SHA} \

        -t gcr.io/$PROJECT_ID/$_IMAGE_NAME:latest \

        --cache-from gcr.io/$PROJECT_ID/$_IMAGE_NAME:latest .
    entrypoint: bash

  # Push container image to registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:${BRANCH_NAME}_${SHORT_SHA}'

  # Deploy container image to dev Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_CLOUD_RUN_SERVICE_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:${BRANCH_NAME}_${SHORT_SHA}'
      - '--region'
      - 'asia-east1'

  # Push container image to registry to update the latest one
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:latest'

timeout: 1200s

images: ['gcr.io/$PROJECT_ID/$_IMAGE_NAME:${BRANCH_NAME}_${SHORT_SHA}', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:latest']

substitutions:
  _IMAGE_NAME: '' # default value
  _CLOUD_RUN_SERVICE_NAME: '' # default value
